language: java

sudo: false

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba/jdk'

addons:
  apt:
    packages:
    - jq
    - curl
    - wget

install:
  # install jabba, if not existent
  - bash ./install-jabba.sh
  - . $HOME/.jabba/jabba.sh
  # install jdk if not installed
  - bash ./install-jdk.sh
  - . $HOME/.jabba/jabba.sh && jabba use adopt-openj9@1.11.0-2
  - export JAVA_HOME="$(. $HOME/.jabba/jabba.sh && jabba which adopt-openj9@1.11.0-2)"

script: mvn -B test


after_success:
  - bash <(curl -s https://codecov.io/bash)
