language: java

sudo: false

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba'

addons:
  apt:
    packages:
    - jq
    - curl
    - wget

before_install:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

install:
  # install jabba, if not existent
  - if [ ! -f ~/.jabba/jabba.sh ]; then curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh; fi
  - . ~/.profile
  # install jdk if not installed
  - if [ -z "$(~/.jabba/jabba.sh which adopt-openj9@1.11.0-2)" ]; then ~/.jabba/jabba.sh install adopt-openj9@1.11.0-2; fi
  - ~/.jabba/jabba.sh use adopt-openj9@1.11.0-2
  - export JAVA_HOME="$(jabba which adopt-openj9@1.11.0-2)" 

after_success:
  - bash <(java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jacoco.xml --projectToken "${CODACY_PROJECT_TOKEN}")
