language: java

sudo: false

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba'

addons:
  apt:
    packages:
    - jq
    - curl
    - wget

install:
  # install jabba, if not existent
  - bash ./install-jabba.sh
  - . ~/.profile
  # install jdk if not installed
  - bash ./install-jdk.sh
  - abba use adopt-openj9@1.11.0-2
  - export JAVA_HOME="$(jabba which adopt-openj9@1.11.0-2)"
  # install code cov jar
  - bash ./install-codecov.sh

# mvn will be run at this point

after_success:
  - bash <(java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jacoco.xml --projectToken "${CODACY_PROJECT_TOKEN}")
