language: java

sudo: false

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba/jdk'

addons:
  apt:
    packages:
    - jq
    - curl
    - wget

install:
  # install jabba, if not existent
  - bash ./install-jabba.sh
  - . $HOME/.jabba/jabba.sh
  # install jdk if not installed
  - bash ./install-jdk.sh
  - . $HOME/.jabba/jabba.sh && jabba use adopt-openj9@1.11.0-2
  - export JAVA_HOME="$(. $HOME/.jabba/jabba.sh && jabba which adopt-openj9@1.11.0-2)"

script: mvn -B test verify


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn --batch-mode org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -Dartifact=com.codacy:codacy-coverage-reporter:4.0.5:jar:assembly -Dtransitive=false -DoutputDirectory=$(pwd)
  - java -jar $(pwd)/codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r report/target/site/jacoco-aggregate/jacoco.xml --project-token "${CODACY_PROJECT_TOKEN}"
